// content/4-component-composition/5-context/vue2/UserProfile.vue
<script>
export default {
  inject: ["user"],
};
</script>

<template>
  <div>
    <h2>My Profile</h2>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <button @click="() => user.updateUsername('Jane')">
      Update username to Jane
    </button>
  </div>
</template>

// content/4-component-composition/5-context/svelte4/UserProfile.svelte
<script>
  import { getContext } from "svelte";

  const userStore = getContext("user");
</script>

<div>
  <h2>My Profile</h2>
  <p>Username: {$userStore.username}</p>
  <p>Email: {$userStore.email}</p>
  <button on:click={() => userStore.updateUsername("Jane")}>
    Update username to Jane
  </button>
</div>
