// content/4-component-composition/2-emit-to-parent/vue2/AnswerButton.vue
<script>
export default {
  methods: {
    clickYes() {
      this.$emit('yes');
    },
    clickNo() {
      this.$emit('no');
    },
  },
};
</script>

<template>
  <div>
    <button @click="clickYes">
      YES
    </button>

    <button @click="clickNo">
      NO
    </button>
  </div>
</template>

// content/4-component-composition/2-emit-to-parent/lit/answer-button.js
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('answer-button')
export class AnswerButton extends LitElement {
	clickYes() {
		this.dispatchEvent(new Event('yes'));
	}

	clickNo() {
		this.dispatchEvent(new Event('no'));
	}

	render() {
		return html`
			<button @click=${this.clickYes}>Yes</button>
			<button @click=${this.clickNo}>No</button>
		`;
	}
}
