// content/6-form-input/2-checkbox/solid/IsAvailable.jsx
import { createSignal } from 'solid-js';

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = createSignal(false);

	function handleChange() {
		setIsAvailable(previousValue => !previousValue);
	}

	return (
		<>
			<input id="is-available" type="checkbox" checked={isAvailable()} onChange={handleChange} />
			<label for="is-available">Is available</label>
		</>
	);
}

// content/6-form-input/2-checkbox/reactTsx/IsAvailable.tsx
import { useState } from "react";
import React from "react";

export default function IsAvailable() {
  const [isAvailable, setIsAvailable] = useState<boolean>(false);

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    setIsAvailable(event.target.checked);
  }

  return (
    <div>
      <label>
        <input type="checkbox" checked={isAvailable} onChange={handleChange} />
        Is available
      </label>
      <p>Available: {isAvailable ? "Yes" : "No"}</p>
    </div>
  );
}
