// content/6-form-input/1-input-text/lit/input-hello.js
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("input-hello")
export class InputHello extends LitElement {
  @state()
  text = "Hello World";

  handleInput(event) {
    this.text = event.target.value;
  }

  render() {
    return html`
      <p>${this.text}</p>
      <input value=${this.text} @input=${this.handleInput} />
    `;
  }
}

// components/2-templating/7-input-binding/InputHello.jsx
import { useState } from "react"

export default function InputHello(){
    const [text, setText] = useState("Hello world");

    function handleChange(event){
        setText(event.target.value)
    }

    return (
        <>
            <p>{text}</p>
            <input value={text} onChange={handleChange} />
        </>
    )
}
