// content/7-webapp-features/2-fetch-data/angularRenaissance/users.component.ts
import { Component, inject } from "@angular/core";
import { UserService } from "./user.service";

@Component({
  selector: "app-users",
  template: `
    @if (userService.usersResource.isLoading()) {
      <div>Fetching users...</div>
    } @else if (userService.usersResource.error()) {
      <p>An error occurred while fetching users</p>
    } @else {
      <ul>
        @for (
          user of userService.usersResource.value()?.results ?? [];
          track user
        ) {
          <li>
            <img [src]="user.picture.thumbnail" alt="user" />
            <p>{{ user.name.first }} {{ user.name.last }}</p>
          </li>
        } @empty {
          <p>No users found</p>
        }
      </ul>
    }
  `,
})
export class UsersComponent {
  protected userService = inject(UserService);
}

// content/7-webapp-features/1-fetch-data/solid/Users.jsx
import { createResource, Show, For } from 'solid-js';

async function fetchUsers() {
	return (await fetch('https://randomuser.me/api/?results=3')).json();
}

export default function Users() {
	const [data] = createResource(fetchUsers);
	const users = () => data()?.results;
	return (
		<Show when={users()}>
			<ul>
				<For each={users()}>
					{(user) => (
						<li>
							<img src={user.picture.thumbnail} alt="user" />
							<p>
								{user.name.first} {user.name.last}
							</p>
						</li>
					)}
				</For>
			</ul>
		</Show>
	);
}
