// content/2-templating/6-conditional/vue3/TrafficLight.vue
<script setup>
import { ref, computed } from "vue";
const TRAFFIC_LIGHTS = ["red", "orange", "green"];
const lightIndex = ref(0);

const light = computed(() => TRAFFIC_LIGHTS[lightIndex.value]);

function nextLight() {
  lightIndex.value = (lightIndex.value + 1) % TRAFFIC_LIGHTS.length;
}
</script>

<template>
  <button @click="nextLight">
    Next light
  </button>
  <p>Light is: {{ light }}</p>
  <p>
    You must
    <span v-if="light === 'red'">STOP</span>
    <span v-else-if="light === 'orange'">SLOW DOWN</span>
    <span v-else-if="light === 'green'">GO</span>
  </p>
</template>

// components/2-templating/6-conditional/TrafficLight.svelte
<script>
    const TRAFFIC_LIGHTS = ["red", 'orange', "green"]
    let lightIndex = 0

    $: light = TRAFFIC_LIGHTS[lightIndex]

    function nextLight(){
        if(lightIndex + 1 > TRAFFIC_LIGHTS.length - 1){
            lightIndex = 0
        } else {
            lightIndex++
        }
        
    }

</script>

<button on:click={nextLight}>Next light</button>
<p>Light is: {light}</p>
<p>
    You must
    {#if light === "red"}
        STOP
    {:else if light === "orange"}
        SLOW DOWN
    {:else if light === "green"}
        GO
    {/if}
</p>
