// content/6-form-input/3-radio/react/PickPill.jsx
import React, { useState } from 'react';

export default function PickPill() {
	const [picked, setPicked] = useState('red');

	function handleChange(event) {
		setPicked(event.target.value);
	}

	return (
		<>
			<div>Picked: {picked}</div>

			<input id="blue-pill" checked={picked === 'blue'} type="radio" value="blue" onChange={handleChange} />
			<label htmlFor="blue-pill">Blue pill</label>

			<input id="red-pill" checked={picked === 'red'} type="radio" value="red" onChange={handleChange} />
			<label htmlFor="red-pill">Red pill</label>
		</>
	);
}

// content/6-form-input/3-radio/angular/pick-pill.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-pick-pill',
	template: `
		<div>Picked: {{ picked }}</div>

		<input id="blue-pill" [checked]="picked === 'blue'" type="radio" value="blue" (change)="handleChange($event)" />
		<label for="blue-pill">Blue pill</label>

		<input id="red-pill" [checked]="picked === 'red'" type="radio" value="red" (change)="handleChange($event)" />
		<label for="red-pill">Red pill</label>
	`,
})
export class PickPillComponent {
	picked = 'red';

	handleChange(event) {
		this.picked = event.target.value;
	}
}
