// content/6-form-input/3-radio/svelte5/PickPill.svelte
<script>
  let picked = $state("red");
</script>

<div>Picked: {picked}</div>

<input id="blue-pill" bind:group={picked} type="radio" value="blue" />
<label for="blue-pill">Blue pill</label>

<input id="red-pill" bind:group={picked} type="radio" value="red" />
<label for="red-pill">Red pill</label>

// content/6-form-input/3-radio/vue2/PickPill.vue
<script>
export default {
  data() {
    return {
      picked: "red",
    };
  },
};
</script>

<template>
  <div>
    <div>Picked: {{ picked }}</div>

    <input id="blue-pill" v-model="picked" type="radio" value="blue" />
    <label for="blue-pill">Blue pill</label>

    <input id="red-pill" v-model="picked" type="radio" value="red" />
    <label for="red-pill">Red pill</label>
  </div>
</template>
