// components/2-templating/7-input-binding/InputHello.jsx
import { useState } from "react"

export default function InputHello(){
    const [text, setText] = useState("Hello world");

    function handleChange(event){
        setText(event.target.value)
    }

    return (
        <>
            <p>{text}</p>
            <input value={text} onChange={handleChange} />
        </>
    )
}

// content/6-form-input/1-input-text/solid/InputHello.jsx
import { createSignal } from "solid-js";

export default function InputHello() {
  const [text, setText] = createSignal("Hello world");

  function handleChange(event) {
    setText(event.target.value);
  }

  return (
    <>
      <p>{text()}</p>
      <input value={text()} onInput={handleChange} />
    </>
  );
}
