// content/7-webapp-features/1-fetch-data/react/App.jsx
import useFetchUsers from './useFetchUsers';

export default function App() {
	const { isLoading, error, data: users } = useFetchUsers();

	return (
		<>
			{isLoading ? (
				<p>Fetching users...</p>
			) : error ? (
				<p>An error occured while fetching users</p>
			) : (
				<ul>
					{users.map((user) => (
						<li key={user.login.uuid}>
							<img src={user.picture.thumbnail} alt="user" />
							<p>
								{user.name.first} {user.name.last}
							</p>
						</li>
					))}
				</ul>
			)}
		</>
	);
}

// content/7-webapp-features/1-fetch-data/svelte/App.svelte
<script>
	import useFetchUsers from './useFetchUsers';

	const { isLoading, error, data: users } = useFetchUsers();
</script>

{#if $isLoading}
	<p>Fetching users...</p>
{:else if $error}
	<p>An error occured while fetching users</p>
{:else if $users}
	<ul>
		{#each $users as user}
			<li>
				<img src={user.picture.thumbnail} alt="user" />
				<p>
					{user.name.first}
					{user.name.last}
				</p>
			</li>
		{/each}
	</ul>
{/if}
