// content/6-form-input/2-checkbox/react/IsAvailable.jsx
import { useState } from 'react';

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = useState(false);

	function handleChange() {
		setIsAvailable(!isAvailable);
	}

	return (
		<>
			<input id="is-available" type="checkbox" checked={isAvailable} onChange={handleChange} />
			<label htmlFor="is-available">Is available</label>
		</>
	);
}

// content/6-form-input/2-checkbox/angular/is-available.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-is-available',
	template: `
		<input id="is-available" type="checkbox" [checked]="isAvailable" (change)="handleChange()" />
		<label for="is-available">Is available</label>
	`,
})
export class IsAvailableComponent {
	isAvailable = false;

	handleChange() {
		this.isAvailable = !this.isAvailable;
	}
}
