// content/3-lifecycle/1-on-mount/qwik/ViewportSize.tsx
import { component$, useClientEffect$, useStore } from "@builder.io/qwik";

export const App = component$(() => {
  const store = useStore({
    viewportSize: "",
  });

  useClientEffect$(() => {
    store.viewportSize = `${window.innerWidth} × ${window.innerHeight}`;
  });

  return <p>Viewport size: {store.viewportSize}</p>;
});

// content/3-lifecycle/1-on-mount/angular/viewportsize.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-viewportsize",
  template: `<p>Viewport size: {{ viewportSize }}</p>`,
})
export class ViewportsizeComponent implements OnInit {
  viewportSize = "";

  ngOnInit() {
    this.viewportSize = `${window.innerWidth} × ${window.innerHeight}`;
  }
}
