// content/4-component-composition/2-emit-to-parent/qwik/AnswerButton.tsx
import { component$, PropFunction } from '@builder.io/qwik';

type Props = {
	onYes$: PropFunction<() => void>;
	onNo$: PropFunction<() => void>;
};

const AnswerButton = component$((props: Props) => {
	return (
		<>
			<button onClick$={props.onYes$}>YES</button>

			<button onClick$={props.onNo$}>NO</button>
		</>
	);
});

export default AnswerButton;

// content/4-component-composition/2-emit-to-parent/react/AnswerButton.jsx
import React from 'react';
import PropTypes from 'prop-types';

export default function AnswerButton({ onYes, onNo }) {
	return (
		<>
			<button onClick={onYes}>YES</button>

			<button onClick={onNo}>NO</button>
		</>
	);
}

AnswerButton.propTypes = {
	onYes: PropTypes.func,
	onNo: PropTypes.func,
};
