// content/4-component-composition/3-slot/qwik/FunnyButton.tsx
import { component$, Slot } from "@builder.io/qwik";

const FunnyButton = component$(() => {
  return (
    <button
      style={{
        background: "rgba(0, 0, 0, 0.4)",
        color: "#fff",
        padding: "10px 20px",
        fontSize: "30px",
        border: "2px solid #fff",
        margin: "8px",
        transform: "scale(0.9)",
        boxShadow: "4px 4px rgba(0, 0, 0, 0.4)",
        transition: "transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s",
        outline: "0",
      }}
    >
      <Slot />
    </button>
  );
});

export default FunnyButton;

// content/4-component-composition/3-slot/reactTsx/FunnyButton.tsx
import React from "react";

interface FunnyButtonProps {
  children: React.ReactNode;
}

export default function FunnyButton({ children }: FunnyButtonProps) {
  return (
    <button
      style={{
        background: "rgba(0, 0, 0, 0.4)",
        color: "#fff",
        padding: "10px 20px",
        fontSize: "30px",
        border: "2px solid #fff",
        margin: "8px",
        transform: "scale(0.9)",
        boxShadow: "4px 4px rgba(0, 0, 0, 0.4)",
        transition: "transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s",
        outline: "0",
      }}
    >
      <p>🤣</p>
      {children}
      <p>🤣</p>
    </button>
  );
}
