// content/6-form-input/1-input-text/qwik/InputHello.tsx
import { component$, useStore, $ } from "@builder.io/qwik";

const InputHello = component$(() => {
  const store = useStore({ text: "" });

  const handleChange = $((event: InputEvent) => {
    store.text = (event.target as HTMLInputElement).value;
  });

  return (
    <>
      <p>{store.text}</p>
      <input value={store.text} onInput$={handleChange} />
    </>
  );
});

export default InputHello;

// content/6-form-input/1-input-text/react/InputHello.jsx
import { useState } from "react";

export default function InputHello() {
  const [text, setText] = useState("Hello world");

  function handleChange(event) {
    setText(event.target.value);
  }

  return (
    <>
      <p>{text}</p>
      <input value={text} onInput={handleChange} />
    </>
  );
}
