// content/6-form-input/4-select/qwik/ColorSelect.tsx
import { component$, useStore, $ } from '@builder.io/qwik';

export const colors = [
	{ id: 1, text: 'red' },
	{ id: 2, text: 'blue' },
	{ id: 3, text: 'green' },
	{ id: 4, text: 'gray', isDisabled: true },
];

const ColorSelect = component$(() => {
	const store = useStore({ selectedColorId: 2 });

	const handleChange = $((event: Event) => {
		store.selectedColorId = Number((event.target as HTMLInputElement).value);
	});

	return (
		<select value={store.selectedColorId} onChange$={handleChange}>
			{colors.map((color) => (
				<option value={color.id} disabled={color.isDisabled}>
					{color.text}
				</option>
			))}
		</select>
	);
});

export default ColorSelect;

// content/6-form-input/4-select/react/ColorSelect.jsx
import React, { useState } from 'react';

const colors = [
	{ id: 1, text: 'red' },
	{ id: 2, text: 'blue' },
	{ id: 3, text: 'green' },
	{ id: 4, text: 'gray', isDisabled: true },
];

export default function ColorSelect() {
	const [selectedColorId, setSelectedColorId] = useState(2);

	function handleChange(event) {
		setSelectedColorId(event.target.value);
	}

	return (
		<select value={selectedColorId} onChange={handleChange}>
			{colors.map((color) => (
				<option key={color.id} value={color.id} disabled={color.isDisabled}>
					{color.text}
				</option>
			))}
		</select>
	);
}
