// content/6-form-input/3-radio/qwik/PickPill.tsx
import { component$, useStore, $ } from "@builder.io/qwik";

const PickPill = component$(() => {
  const store = useStore({ picked: "red" });

  const handleChange = $((event: Event) => {
    store.picked = (event.target as HTMLInputElement).value;
  });

  return (
    <>
      <div>Picked: {store.picked}</div>
      <input
        id="blue-pill"
        checked={store.picked === "blue"}
        type="radio"
        value="blue"
        onChange$={handleChange}
      />
      <label for="blue-pill">Blue pill</label>

      <input
        id="red-pill"
        checked={store.picked === "red"}
        type="radio"
        value="red"
        onChange$={handleChange}
      />
      <label for="red-pill">Red pill</label>
    </>
  );
});

export default PickPill;

// content/6-form-input/3-radio/react/PickPill.jsx
import React, { useState } from 'react';

export default function PickPill() {
	const [picked, setPicked] = useState('red');

	function handleChange(event) {
		setPicked(event.target.value);
	}

	return (
		<>
			<div>Picked: {picked}</div>

			<input id="blue-pill" checked={picked === 'blue'} type="radio" value="blue" onChange={handleChange} />
			<label htmlFor="blue-pill">Blue pill</label>

			<input id="red-pill" checked={picked === 'red'} type="radio" value="red" onChange={handleChange} />
			<label htmlFor="red-pill">Red pill</label>
		</>
	);
}
