// content/2-templating/5-dom-ref/qwik/InputFocused.tsx
import { component$, useVisibleTask$, useSignal } from "@builder.io/qwik";

export const InputFocused = component$(() => {
  const inputElement = useSignal<HTMLInputElement>();
  
  useVisibleTask$(({ track }) => {
    const el = track(inputElement);
    el?.focus();
  });

  return <input type="text" ref={inputElement} />;
});

// content/2-templating/5-dom-ref/angular/inputfocused.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit } from '@angular/core';

@Component({
	selector: 'app-inputfocused',
	template: '<input type="text" #inputelement />',
})
export class InputfocusedComponent implements AfterViewInit {
	@ViewChild('inputelement')
	inputElement: ElementRef<HTMLInputElement> | undefined;

	ngAfterViewInit(): void {
		this.inputElement?.nativeElement.focus();
	}
}

<input type="text" #inputelement />
