// content/3-lifecycle/2-on-unmount/react/Time.jsx
import { useState, useEffect } from "react";

export default function Time() {
  const [time, setTime] = useState(new Date().toLocaleTimeString());

  useEffect(() => {
    const timer = setInterval(() => {
      setTime(new Date().toLocaleTimeString());
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  return <p>Current time: {time}</p>;
}

// content/3-lifecycle/2-on-unmount/solid/Time.jsx
import { createSignal, onCleanup } from 'solid-js';

export default function Time() {
	const [time, setTime] = createSignal(new Date().toLocaleTimeString());

	const timer = setInterval(() => {
		setTime(new Date().toLocaleTimeString());
	}, 1000);

	onCleanup(() => clearInterval(timer));

	return <p>Current time: {time()}</p>;
}
