// components/3-lifecycle/2-onUnmount/Time.vue
<script setup>
    import { ref, onUnmounted } from "svelte"

    const time = ref(new Date().toLocaleTimeString())

    const timer = setInterval( () => {
        time.value = new Date().toLocaleTimeString()
     }, 1000);

     onUnmounted(() => {
        clearInterval(timer)
     })
</script>

<p>Current time: {time}</p>

// components/3-lifecycle/2-onUnmount/Time.jsx
import {useState, useEffect} from "react"

export default function Time(){
    const [time, setTime] = useState(new Date().toLocaleTimeString());

    const timer = setInterval( () => {
        setTime(new Date().toLocaleTimeString())
     }, 1000);

    useEffect(() => {
        return () => {
            clearInterval(timer)
        }
    })

    return <p>Current time: {time}</p>
}
