// components/2-templating/6-conditional/TrafficLight.vue
<script setup>
    import { ref, computed } from "vue"
    const TRAFFIC_LIGHTS = ["red", 'orange', "green"]
    const lightIndex = ref(0)

    const light = computed(() => TRAFFIC_LIGHTS[lightIndex])

    function nextLight(){
        if(lightIndex.value + 1 > TRAFFIC_LIGHTS.length - 1){
            lightIndex.value = 0
        } else {
            lightIndex.value++
        }
    }

</script>

<button @click="nextLight">Next light</button>
<p>Light is: {{light}}</p>
<p>
    You must
    <span v-if="light === 'red'">STOP</span>
    <span v-else-if="light === 'orange'">SLOW DOWN</span>
    <span v-else-if="light === 'green'">GO</span>
</p>

// content/2-templating/6-conditional/svelte4/TrafficLight.svelte
<script>
  const TRAFFIC_LIGHTS = ["red", "orange", "green"];
  let lightIndex = 0;

  $: light = TRAFFIC_LIGHTS[lightIndex];

  function nextLight() {
    lightIndex = (lightIndex + 1) % TRAFFIC_LIGHTS.length;
  }
</script>

<button on:click={nextLight}>Next light</button>
<p>Light is: {light}</p>
<p>
  You must
  {#if light === "red"}
    <span>STOP</span>
  {:else if light === "orange"}
    <span>SLOW DOWN</span>
  {:else if light === "green"}
    <span>GO</span>
  {/if}
</p>
