// content/7-webapp-features/1-fetch-data/react/App.jsx
import useFetchUsers from './useFetchUsers';

export default function App() {
	const { isLoading, error, data: users } = useFetchUsers();

	return (
		<>
			{isLoading ? (
				<p>Fetching users...</p>
			) : error ? (
				<p>An error occured while fetching users</p>
			) : (
				<ul>
					{users.map((user) => (
						<li key={user.login.uuid}>
							<img src={user.picture.thumbnail} alt="user" />
							<p>
								{user.name.first} {user.name.last}
							</p>
						</li>
					))}
				</ul>
			)}
		</>
	);
}

// content/7-webapp-features/1-fetch-data/vue3/App.vue
<script setup>
import useFetchUsers from './useFetchUsers';

const { isLoading, error, data: users } = useFetchUsers();
</script>

<template>
  <p v-if="isLoading">
    Fetching users...
  </p>
  <p v-else-if="error">
    An error ocurred while fetching users
  </p>
  <ul v-else>
    <li
      v-for="user in users"
      :key="user.login.uuid"
    >
      <img
        :src="user.picture.thumbnail"
        alt="user"
      >
      <p>
        {{ user.name.first }}
        {{ user.name.last }}
      </p>
    </li>
  </ul>
</template>
