// content/4-component-composition/5-context/solid/App.jsx
import { createContext, createState, useState } from 'solid-js'
import UserProfile from './UserProfile'

const UserContext = createContext();

export default function App() {
  const [user, setUser] = useState({
    id: 1,
    username: "unicorn42",
    email: "unicorn42@example.com",
  });

  function updateUsername(newUsername) {
    setUser(userData => ({ ...userData, username: newUsername }));
  }

  return (
    <UserContext.Provider value={{ user, updateUsername }}>
      <>
        <h1>Welcome back, {user.username}</h1>
        <UserProfile />
      </>
    </UserContext.Provider>
  );
}

// content/4-component-composition/5-context/qwik/App.tsx
import {
  component$,
  useStore,
  useContextProvider,
  createContext,
  $,
} from "@builder.io/qwik";
import UserProfile from "./UserProfile";

export const UserContext = createContext("user-context");

const App = component$(() => {
  const user = useStore({
    id: 1,
    username: "unicorn42",
    email: "unicorn42@example.com",
  });

  const updateUsername = $((newUsername) => {
    user.username = newUsername;
  });

  useContextProvider(UserContext, { user, updateUsername });

  return (
    <>
      <h1>Welcome back, {user.username}</h1>
      <UserProfile />
    </>
  );
});

export default App;
