// content/4-component-composition/5-context/react/UserProfile.jsx
import { useContext } from "react";
import { UserContext } from "./App";

export default function UserProfile() {
  const { username, email, updateUsername } = useContext(UserContext);

  return (
    <div>
      <h2>My Profile</h2>
      <p>Username: {username}</p>
      <p>Email: {email}</p>
      <button onClick={() => updateUsername("Jane")}>
        Update username to Jane
      </button>
    </div>
  );
}

// content/4-component-composition/5-context/qwik/UserProfile.tsx
import { component$, useContext } from "@builder.io/qwik";
import { UserContext } from "./App";

const UserProfile = component$(() => {
  const { user, updateUsername } = useContext(UserContext);

  return (
    <div>
      <h2>My Profile</h2>
      <p>Username: {user.username}</p>
      <p>Email: {user.email}</p>
      <button onClick$={() => updateUsername("Jane")}>
        Update username to Jane
      </button>
    </div>
  );
});

export default UserProfile;
