// content/2-templating/4-event-click/solid/Counter.jsx
import { createSignal } from "solid-js";

export default function Counter() {
  const [count, setCount] = createSignal(0);

  function incrementCount() {
    setCount(count() + 1);
  }

  return (
    <>
      <p>Counter: {count()}</p>
      <button onClick={incrementCount}>+1</button>
    </>
  );
}

// components/2-templating/4-event-click/react/Counter.jsx
import { useState } from "react"

export default function Name(){
    const [count, setCount] = useState(0);

    function incrementCount(){
        setCount(count + 1)
    }
    
    return (
        <>
            <p>Counter: {count}</p>
            <button onClick={incrementCount}>+1</button>
        </>
    )
}
