// content/2-templating/4-event-click/qwik/Counter.tsx
import { component$, useStore } from "@builder.io/qwik";

export const Counter = component$(() => {
  const store = useStore({ count: 0 });

  const incrementCount = () => {
    store.count++;
  };

  return (
    <>
      <p>Counter: {store.count}</p>
      <button onClick$={incrementCount}>Increment</button>
    </>
  );
});

// components/2-templating/4-event-click/react/Counter.jsx
import { useState } from "react"

export default function Name(){
    const [count, setCount] = useState(0);

    function incrementCount(){
        setCount(count + 1)
    }
    
    return (
        <>
            <p>Counter: {count}</p>
            <button onClick={incrementCount}>+1</button>
        </>
    )
}
