// content/2-templating/4-event-click/angular/counter.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-counter',
	template: `
		<p>Counter: {{ count }}</p>
		<button (click)="incrementCount()">+1</button>
	`,
})
export class CounterComponent {
	count = 0;

	incrementCount() {
		this.count++;
	}
}

<p>Counter: {{ count }}</p>
<button (click)="incrementCount()">+1</button>

// components/2-templating/4-event-click/react/Counter.jsx
import { useState } from "react"

export default function Name(){
    const [count, setCount] = useState(0);

    function incrementCount(){
        setCount(count + 1)
    }
    
    return (
        <>
            <p>Counter: {count}</p>
            <button onClick={incrementCount}>+1</button>
        </>
    )
}
