// content/2-templating/2-styling/lit/css-style.js
import { LitElement, html, css } from "lit";
import { customElement } from "lit/decorators.js";
import { styleMap } from "lit/directives/style-map.js";

@customElement("css-style")
export class CssStyle extends LitElement {
  static styles = css`
    .title {
      color: red;
    }
  `;

  render() {
    return html`
      <h1 class="title">I am red</h1>
      <button style=${styleMap({ fontSize: "10rem" })}>I am a button</button>
    `;
  }
}

// content/2-templating/2-styling/angularRenaissance/cssstyle.component.ts
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "app-cssstyle",
  template: `
    <h1 class="title">I am red</h1>
    <button style="font-size: 10rem">I am a button</button>
  `,
  styles: `
    .title {
      color: red;
    }
  `,
})
export class CssStyleComponent {}
