// content/2-templating/2-styling/qwik/CssStyle.tsx
import { component$, useStyles$ } from "@builder.io/qwik";

export const App = component$(() => {
  useStyles$(`
    .title {
      color: red;
    }
    `);

  return (
    <>
      <h1 class="title">I am red</h1>
      <button style={{ "font-size": "10rem" }}>I am a button</button>
    </>
  );
});

// content/2-templating/2-styling/angularRenaissance/cssstyle.component.ts
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "app-cssstyle",
  template: `
    <h1 class="title">I am red</h1>
    <button style="font-size: 10rem">I am a button</button>
  `,
  styles: `
    .title {
      color: red;
    }
  `,
})
export class CssStyleComponent {}
