// content/6-form-input/2-checkbox/solid/IsAvailable.jsx
import { createSignal } from 'solid-js';

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = createSignal(false);

	function handleChange() {
		setIsAvailable(previousValue => !previousValue);
	}

	return (
		<>
			<input id="is-available" type="checkbox" checked={isAvailable()} onChange={handleChange} />
			<label for="is-available">Is available</label>
		</>
	);
}

// content/6-form-input/2-checkbox/react/IsAvailable.jsx
import { useState } from 'react';

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = useState(false);

	function handleChange() {
		setIsAvailable(!isAvailable);
	}

	return (
		<>
			<input id="is-available" type="checkbox" checked={isAvailable} onChange={handleChange} />
			<label htmlFor="is-available">Is available</label>
		</>
	);
}
