// content/6-form-input/4-select/vue3/ColorSelect.vue
<script setup>
import { ref } from 'vue';

const selectedColorId = ref(2);

const colors = [
	{ id: 1, text: 'red' },
	{ id: 2, text: 'blue' },
	{ id: 3, text: 'green' },
	{ id: 4, text: 'gray', isDisabled: true },
];
</script>

<template>
	<select v-model="selectedColorId">
		<option v-for="color in colors" :key="color.id" :value="color.id" :disabled="color.isDisabled">
			{{ color.text }}
		</option>
	</select>
</template>

// content/6-form-input/4-select/svelte5/ColorSelect.svelte
<script>
  let selectedColorId = $state(2);

  const colors = [
    { id: 1, text: "red" },
    { id: 2, text: "blue" },
    { id: 3, text: "green" },
    { id: 4, text: "gray", isDisabled: true },
  ];
</script>

<select bind:value={selectedColorId}>
  {#each colors as color}
    <option value={color.id} disabled={color.isDisabled}>
      {color.text}
    </option>
  {/each}
</select>
