// content/3-lifecycle/1-on-mount/qwik/ViewportSize.tsx
import { component$, useClientEffect$, useStore } from "@builder.io/qwik";

export const App = component$(() => {
  const store = useStore({
    viewportSize: "",
  });

  useClientEffect$(() => {
    store.viewportSize = `${window.innerWidth} × ${window.innerHeight}`;
  });

  return <p>Viewport size: {store.viewportSize}</p>;
});

// content/3-lifecycle/1-on-mount/lit/viewport-size.js
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("viewport-size")
export class ViewportSize extends LitElement {
  @state()
  viewportSize = "";

  connectedCallback() {
    super.connectedCallback();
    this.viewportSize = `${window.innerWidth} × ${window.innerHeight}`;
  }

  render() {
    return html`<p>Viewport size: ${this.viewportSize}</p>`;
  }
}
