// content/6-form-input/3-radio/solid/PickPill.jsx
import { createSignal } from "solid-js";

export default function PickPill() {
  const [picked, setPicked] = createSignal("red");

  function handleChange(event) {
    setPicked(event.target.value);
  }

  return (
    <>
      <div>Picked: {picked()}</div>
      <input
        id="blue-pill"
        checked={picked() === "blue"}
        type="radio"
        value="blue"
        onChange={handleChange}
      />
      <label for="blue-pill">Blue pill</label>

      <input
        id="red-pill"
        checked={picked() === "red"}
        type="radio"
        value="red"
        onChange={handleChange}
      />
      <label for="red-pill">Red pill</label>
    </>
  );
}

// content/6-form-input/3-radio/reactTsx/PickPill.tsx
import { useState } from "react";
import React from "react";

export default function PickPill() {
  const [picked, setPicked] = useState<string>("");

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    setPicked(event.target.value);
  }

  return (
    <div>
      <p>Which pill will you take?</p>
      <label>
        <input
          type="radio"
          value="red"
          checked={picked === "red"}
          onChange={handleChange}
        />
        Red
      </label>
      <label>
        <input
          type="radio"
          value="blue"
          checked={picked === "blue"}
          onChange={handleChange}
        />
        Blue
      </label>
      {picked && <p>You picked the {picked} pill.</p>}
    </div>
  );
}
