// content/4-component-composition/2-emit-to-parent/angular/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  template: `
    <p>Can I come?</p>

    <app-answer-button (yes)="onAnswerYes()" (no)="onAnswerNo()">
    </app-answer-button>

    <p style="font-size: 50px">{{ canCome ? "😀" : "😥" }}</p>
  `,
})
export class AppComponent {
  canCome = true;

  onAnswerYes() {
    this.canCome = true;
  }

  onAnswerNo() {
    this.canCome = false;
  }
}

<p>Can I come ?</p>
<app-answer-button (yes)="onAnswerYes()" (no)="onAnswerNo()"> </app-answer-button>
<p style="font-size: 50px">{{ canCome ? '😀' : '😥' }}</p>

// content/4-component-composition/2-emit-event/vue3/App.vue
<script setup>
import { ref } from 'vue';
import AnswerButton from './AnswerButton.vue';

let canCome = ref(true);

function onAnswerNo() {
	canCome.value = false;
}

function onAnswerYes() {
	canCome.value = true;
}
</script>

<template>
	<p>Can I come ?</p>
	<AnswerButton @yes="onAnswerYes" @no="onAnswerNo" />
	<p style="font-size: 50px">
		{{ canCome ? '😀' : '😥' }}
	</p>
</template>
