// content/4-component-composition/1-props/solid/UserProfile.jsx
import { mergeProps } from "solid-js";

export default function UserProfile(props) {
  const merged = mergeProps(
    { name: "", age: null, favouriteColors: [], isAvailable: false },
    props
  );

  return (
    <>
      <p>My name is {merged.name} !</p>
      <p>My age is {merged.age} !</p>
      <p>My favourite colors are {merged.favouriteColors.join(", ")} !</p>
      <p>I am {merged.isAvailable ? "available" : "not available"}</p>
    </>
  );
}

// content/4-component-composition/1-props/svelte/UserProfile.svelte
<script>
  export let name = "";
  export let age = null;
  export let favouriteColors = [];
  export let isAvailable = false;
</script>

<p>My name is {name} !</p>
<p>My age is {age} !</p>
<p>My favourite colors are {favouriteColors.join(", ")} !</p>
<p>I am {isAvailable ? "available" : "not available"}</p>
