// content/4-component-composition/1-props/qwik/UserProfile.tsx
import { component$ } from "@builder.io/qwik";

type Props = {
  name: string;
  age: number;
  favouriteColors: string[];
  isAvailable: boolean;
};

const UserProfile = component$((props: Props) => {
  const {
    name = "",
    age = null,
    favouriteColors = [],
    isAvailable = false,
  } = props;

  return (
    <>
      <p>My name is {name} !</p>
      <p>My age is {age} !</p>
      <p>My favourite colors are {favouriteColors.join(", ")} !</p>
      <p>I am {isAvailable ? "available" : "not available"}</p>
    </>
  );
});

export default UserProfile;

// content/4-component-composition/1-props/svelte/UserProfile.svelte
<script>
  export let name = "";
  export let age = null;
  export let favouriteColors = [];
  export let isAvailable = false;
</script>

<p>My name is {name} !</p>
<p>My age is {age} !</p>
<p>My favourite colors are {favouriteColors.join(", ")} !</p>
<p>I am {isAvailable ? "available" : "not available"}</p>
