// components/3-lifecycle/2-onUnmount/Time.jsx
import {useState, useEffect} from "react"

export default function Time(){
    const [time, setTime] = useState(new Date().toLocaleTimeString());

    const timer = setInterval( () => {
        setTime(new Date().toLocaleTimeString())
     }, 1000);

    useEffect(() => {
        return () => {
            clearInterval(timer)
        }
    })

    return <p>Current time: {time}</p>
}

// content/3-lifecycle/2-on-unmount/svelte5/Time.svelte
<script>
  import { onDestroy } from "svelte";

  let time = $state(new Date().toLocaleTimeString());

  onDestroy(() => {
    const timer = setInterval(() => {
      time = new Date().toLocaleTimeString();
    }, 1000);

    return () => clearInterval(timer);
  });
</script>

<p>Current time: {time}</p>
