// content/4-component-composition/5-context/svelte5/App.svelte
<script>
  import { setContext } from "svelte";
  import UserProfile from "./UserProfile.svelte";
  import createUserState from "./createUserState.svelte.js";

  const user = createUserState({
    id: 1,
    username: "unicorn42",
    email: "unicorn42@example.com",
  });

  setContext("user", user);
</script>

<h1>Welcome back, {user.username}</h1>
<UserProfile />

// content/4-component-composition/5-context/vue2/App.vue
<script>
import UserProfile from "./UserProfile.vue";

export default {
  components: { UserProfile },
  provide() {
    return {
      user: Object.assign(this.user, {
        updateUsername: this.updateUsername,
      }),
    };
  },
  data() {
    return {
      user: {
        id: 1,
        username: "unicorn42",
        email: "unicorn42@example.com",
      },
    };
  },
  methods: {
    updateUsername(newUsername) {
      this.user.username = newUsername;
    },
  },
};
</script>

<template>
  <div>
    <h1>Welcome back, {{ user.username }}</h1>
    <UserProfile />
  </div>
</template>
